framework:
    secret: '%env(APP_SECRET)%'

    # Stateless API
    # JWT at Bearer header + HttpOnly cookie for refresh token.
    session: false

    http_method_override: false

    handle_all_throwables: true

# PHPUnit
when@test:
    framework:
        test: true
