identity_controllers:
    resource:
        path: '../src/Identity/Infrastructure/Delivery/Http/Controller/'
        namespace: 'App\Identity\Infrastructure\Delivery\Http\Controller'
    type: attribute
